services:

  cap:
    image: "node:lts"
    user: "node"
    working_dir: /home/node/app
    environment:
      - PORT=443
      - NODE_ENV=production
      - NODE_EXTRA_CA_CERTS=/home/node/app/ssl/ca/ca.crt
      - CF_INSTANCE_CERT=/home/node/app/ssl/servers/cap.crt
      - CF_INSTANCE_KEY=/home/node/app/ssl/servers/cap.key
      - FS_MOUNT=/home/node/persistence
    volumes:
      - ./:/home/node/app
    develop:
      watch:
        - path: ./srv
          action: restart
    ports:
      - "5000:53/udp"
      - "4000:443"
      - "9000:9229"
    command: ["npm", "run", "debug"]

  sap.cap:
    image: "node:lts"
    user: "node"
    working_dir: /home/node/app
    environment:
      - PORT=443
      - NODE_ENV=production
      - NODE_EXTRA_CA_CERTS=/home/node/app/ssl/ca/ca.crt
      - CF_INSTANCE_CERT=/home/node/app/ssl/servers/sap.cap.crt
      - CF_INSTANCE_KEY=/home/node/app/ssl/servers/sap.cap.key
      - FS_MOUNT=/home/node/persistence
    volumes:
      - ./:/home/node/app
    develop:
      watch:
        - path: ./srv
          action: restart
    ports:
      - "5001:53/udp"
      - "4001:443"
      - "9001:9229"
    command: ["npm", "run", "debug"]

networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 172.28.208.0/20
        gateway: 172.28.208.1
