[req]
distinguished_name = req_distinguished_name
x509_extensions = v3_ca
prompt = no

[req_distinguished_name]
C = DE
ST = Baden-Württemberg
L = Walldorf
O = SAP SE
OU = CAP
CN = CAP Root CA
emailAddress = cap@sap.com

[v3_ca]
basicConstraints = critical,CA:true,pathlen:0
keyUsage = critical,keyCertSign,cRLSign
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer